# Pandas Data Management

Load data.

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

# DataFrame Copy
df_original = df.copy()

c:\Users\hp\anaconda3\envs\Data_Analysis\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Copy

Recall from the last lesson, when we filled in missing values for median salary.

Here let's make a new dataframe `df_altered` and only make changes to it.

In [2]:
# Create new dataframe
df_altered = df_original

df_altered.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

Let's fill in missing values with the median value.

In [3]:
# Calculating the median salary
median_salary = df_altered['salary_year_avg'].median()

# Filling the missing values with the median salary
df_altered['salary_year_avg'] = df_altered.loc[:,'salary_year_avg'].fillna(median_salary)

In [4]:
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

Now let's inspect the altered DataFrame.

In [5]:
df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

That was good...

But what about the original...

In [6]:
df_original.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

Holdup!! How the heck did `df_original` get altered!?!

Well both the variables of `df_original` and `df_altered` are referencing the same DataFrame.

In [7]:
print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                1849004233808
ID of df_altered:                 1849004233808
Are the two dataframes the same?  True

Instead we can use the .copy() method

- `copy()`: Copy a DataFrame.

In [8]:
df_original = df.copy()
df_altered = df_original.copy()

print('ID of df_original:               ', id(df_original))
print('ID of df_altered:                ', id(df_altered))
print('Are the two dataframes the same? ', id(df_original) == id(df_altered))

ID of df_original:                1849004234128
ID of df_altered:                 1849004579440
Are the two dataframes the same?  False

Now when we do this same operation:

In [9]:
# Calculating the median salary
median_salary = df_altered['salary_year_avg'].median()

# Filling the missing values with the median salary
df_altered['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5,'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

The original dataframe doesn't get altered!

In [10]:
df_original.loc[:5,'salary_year_avg']

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

Now that we've created a copy of our data, we want to start our analysis. But if we have a large set of data we only want to take a subset of data to make it more manageable. We can use `sample()` to get a random sample of the data.

## Sample

### Notes

* `sample()`: Random sample of items.

### Examples

Let's get a random sample of the data. You could get a sample with a fixed row number.

In [11]:
df.sample(n=5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
184039,Data Scientist,Data Scientist,"Dublin, Ireland",via LinkedIn,Contractor and Temp work,False,Ireland,2023-10-10 15:33:15,False,False,Ireland,None,NaN,NaN,Harvey Nash,['sql'],{'programming': ['sql']}
758852,Data Scientist,Data Scientist,"Remote, OR",via Indeed,Full-time,False,"California, United States",2023-06-23 20:21:28,False,True,United States,None,NaN,NaN,Pie Insurance,"['python', 'sql', 'mysql', 'sql server', 'snow...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
451772,Data Scientist,DATA SCIENTIST (PhD),"Paris, France",via LinkedIn,Full-time,False,France,2023-02-21 14:42:51,False,False,France,None,NaN,NaN,Wisear,"['python', 'tensorflow', 'pytorch', 'jupyter',...","{'libraries': ['tensorflow', 'pytorch', 'jupyt..."
432865,Senior Data Scientist,"Senior Data Scientist, Marketing & Online (Rem...","Atlanta, GA",via WJHL Jobs,Full-time,False,Georgia,2023-02-09 17:26:35,False,False,United States,None,NaN,NaN,Home Depot,"['python', 'sql', 'bigquery', 'excel', 'tableau']","{'analyst_tools': ['excel', 'tableau'], 'cloud..."
543342,Senior Data Scientist,Senior Statistical Analyst,"Leuven, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-04-16 20:10:02,False,False,Belgium,None,NaN,NaN,"Medpace, Inc.","['sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sa..."

Or you can randomly select a fraction of the data (e.g., 10% of the rows), with or without replacement.

In [12]:
df.sample(frac=0.1, replace=False)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
22906,Data Scientist,Junior Data Scientist,"Hengelo, Netherlands",via LinkedIn,Full-time,False,Netherlands,2023-08-07 14:16:03,False,False,Netherlands,None,NaN,NaN,StarApple,"['scala', 'python', 'sql', 'r']","{'programming': ['scala', 'python', 'sql', 'r']}"
473264,Data Scientist,Data Science Manager,Anywhere,via LinkedIn,Full-time,True,Poland,2023-11-24 14:16:14,False,False,Poland,None,NaN,NaN,Addepto,"['python', 'sql', 'nosql', 'azure', 'aws', 'py...","{'cloud': ['azure', 'aws'], 'libraries': ['pyt..."
722854,Data Analyst,Medior data analyst,"Brussels, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-07-20 21:54:43,True,False,Belgium,None,NaN,NaN,Pauwels Consulting,['azure'],{'cloud': ['azure']}
414145,Senior Data Scientist,"Senior Data Scientist, Product Growth",Florida,via SimplyHired,Full-time,False,"Florida, United States",2023-12-18 16:03:36,False,False,United States,None,NaN,NaN,Jerry,['sql'],{'programming': ['sql']}
380932,Data Engineer,Lead Data Engineer,"Porto, Portugal",via Ai-Jobs.net,Full-time,False,Portugal,2023-06-27 18:51:22,False,False,Portugal,year,131580.0,NaN,Mindera,['aws'],{'cloud': ['aws']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280767,Data Analyst,Marketing Data Analyst,New Zealand,via Trabajo.org,Full-time,False,New Zealand,2023-12-08 07:24:36,False,False,New Zealand,None,NaN,NaN,Seequent,"['sql', 'excel', 'power bi']","{'analyst_tools': ['excel', 'power bi'], 'prog..."
375067,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-02-26 18:06:01,False,False,United States,None,NaN,NaN,Editech Staffing,"['nosql', 'sql', 'python', 'scala', 'java', 'c...","{'cloud': ['azure', 'redshift', 'snowflake'], ..."
378325,Data Analyst,SAP Data Analyst I,"Waukesha, WI",via My Stateline Jobs,Full-time,False,"Illinois, United States",2023-06-16 18:18:22,True,False,United States,None,NaN,NaN,Generac Power Systems,['sap'],{'analyst_tools': ['sap']}
169831,Software Engineer,Senior C# Software Engineer,"Athens, Greece",via SmartRecruiters Job Search,Full-time,False,Greece,2023-05-29 15:30:44,False,False,Greece,None,NaN,NaN,OpenBet,"['c#', 'sql', 'python', 'no-sql', 'mongodb', '...","{'async': ['jira', 'confluence'], 'databases':..."
671523,Senior Data Engineer,Senior Data Engineer (Java),"Chennai, Tamil Nadu, India",via LinkedIn,Full-time,False,India,2023-04-06 10:15:28,False,False,India,None,NaN,NaN,Marlabs LLC,"['java', 'sql', 'python', 'aws', 'kafka']","{'cloud': ['aws'], 'libraries': ['kafka'], 'pr..."

Now you can analyze these subsets of data.